/*  DB-WEAVE textile CAD/CAM software - http://www.brunoldsoftware.ch
    Copyright (C) 1998  Damian Brunold
    Copyright (C) 2009  Damian Brunold

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
/*-----------------------------------------------------------------*/
#include <vcl\vcl.h>
#pragma hdrstop
/*-----------------------------------------------------------------*/
#include "dbw3_form.h"
#include "dbw3_strings.h"
#include "language.h"
/*-----------------------------------------------------------------*/
void __fastcall TDBWFRM::ReloadLanguage()
{
    // Menüs
      // Menu Datei
      LANG_C_H(MenuDatei, EN, "&File", "")
      LANG_C_H(MenuDatei, GE, "&Datei", "")
      LANG_C_H(FileNew, EN, "&New", "Creates a new pattern")
      LANG_C_H(FileNew, GE, "&Neu", "Erstellt ein neues Muster")
      LANG_C_H(FileNewTemplate, EN, "New &from template...", "Creates a new pattern based upon a template")
      LANG_C_H(FileNewTemplate, GE, "Neu ge&mäss Vorlage...", "Erstellt ein neues Muster anhand einer Vorlage")
      LANG_C_H(FileOpen, EN, "&Open...", "Opens a pattern")
      LANG_C_H(FileOpen, GE, "Ö&ffnen...", "Öffnet ein Muster")
      LANG_C_H(LoadParts, EN, "&Load parts...", "Loads only parts of a pattern into the current pattern")
      LANG_C_H(LoadParts, GE, "&Teile laden...", "Lädt Teile eines Musters in das aktuelle Muster")
      LANG_C_H(FileSave, EN, "&Save", "Saves the pattern")
      LANG_C_H(FileSave, GE, "&Speichern", "Speichert das Muster")
      LANG_C_H(FileSaveas, EN, "Save &as...", "Saves the pattern to a new file")
      LANG_C_H(FileSaveas, GE, "Speichern &unter...", "Speichert das Muster unter einem neuen Namen")
      LANG_C_H(FileRevert, EN, "Revert &changes", "Discards any changes and restores the last saved state of the pattern")
      LANG_C_H(FileRevert, GE, "Änderungen ver&werfen", "Verwirft alle Änderungen und kehrt zum letzten gespeicherten Zustand zurück")
      LANG_C_H(DateiImport, EN, "I&mport", "Imports a pattern from another program")
      LANG_C_H(DateiImport, GE, "I&mport", "Importiert ein Muster eines anderen Programmes")
      LANG_C_H(DateiExport, EN, "&Export", "Exports the pattern to other programs")
      LANG_C_H(DateiExport, GE, "E&xportieren", "Exportiert das Muster in andere Programme")
      LANG_C_H(ImportWIF, EN, "&WIF file...", "Imports the pattern from a WIF file")
      LANG_C_H(ImportWIF, GE, "&WIF Datei...", "Importiert das Muster einer WIF Datei")
      LANG_C_H(ExportBitmap, EN, "&Bitmap file...", "Exports the pattern to a bitmap file")
      LANG_C_H(ExportBitmap, GE, "&Bitmap Datei...", "Exportiert das Muster in eine Bilddatei")
      LANG_C_H(ExportWIF, EN, "&WIF file...", "Exports the pattern to a WIF file")
      LANG_C_H(ExportWIF, GE, "&WIF Datei...", "Exportiert das Muster in eine WIF Datei")
      LANG_C_H(ExportDBW35, EN, "&DB-WEAVE 3.5 file...", "Exports the pattern to a DB-WEAVE 3.5 file")
      LANG_C_H(ExportDBW35, GE, "&DB-WEAVE 3.5 Datei...", "Exportiert das Muster in eine DB-WEAVE 3.5 Datei")
      LANG_C_H(FileProps, EN, "Propert&ies...", "Edits the properties of the pattern")
      LANG_C_H(FileProps, GE, "&Eigenschaften...", "Bearbeitet die Eigenschaften des Musters")
      LANG_C_H(FileSetPage, EN, "Page se&tup...", "Sets the page margins and headers and footers")
      LANG_C_H(FileSetPage, GE, "Se&ite einrichten...", "Richtet die Seitenränder und Kopf- und Fusszeilen ein")
      LANG_C_H(FilePrintpreview, EN, "Print pre&view", "Shows how the pattern will be printed")
      LANG_C_H(FilePrintpreview, GE, "Druckvorsc&hau", "Zeigt wie das Muster gedruckt wird")
      LANG_C_H(FilePrint, EN, "&Print...", "Prints the pattern")
      LANG_C_H(FilePrint, GE, "&Drucken...", "Druckt das Muster")
      LANG_C_H(OptPrintSelection, EN, "P&rint part...", "Prints only a part of the pattern")
      LANG_C_H(OptPrintSelection, GE, "Teil dru&cken...", "Druckt nur einen Teil des Musters")
      LANG_C_H(FilePrintSetup, EN, "Printer set&up...", "Configures the printer")
      LANG_C_H(FilePrintSetup, GE, "D&ruckereinstellung...", "Konfiguriert den Drucker")
      LANG_C_H(FileExit, EN, "E&xit", "Exits the program")
      LANG_C_H(FileExit, GE, "&Beenden", "Beendet das Programm")


      // Menu Bearbeiten
      LANG_C_H(MenuBearbeiten, EN, "&Edit", "")
      LANG_C_H(MenuBearbeiten, GE, "&Bearbeiten", "")
      LANG_C_H(EditUndo, EN, "&Undo", "Undoes the last action")
      LANG_C_H(EditUndo, GE, "&Rückgängig", "Macht die letzte Änderung rückgängig")
      LANG_C_H(EditRedo, EN, "&Redo", "Redoes the last undone action")
      LANG_C_H(EditRedo, GE, "&Wiederholen", "Führt die letzte rückgängig gemachte Änderung durch")
      LANG_C_H(EditCut, EN, "Cu&t", "Cuts the selection to the clipboard")
      LANG_C_H(EditCut, GE, "A&usschneiden", "Schneidet die Selektion aus und kopiert sie in die Zwischenablage")
      LANG_C_H(EditCopy, EN, "&Copy", "Copies the selection to the clipboard")
      LANG_C_H(EditCopy, GE, "&Kopieren", "Kopiert die Selektion in die Zwischenablage")
      LANG_C_H(EditPaste, EN, "&Paste", "Pastes the contents of the clipboard at the current cursor location")
      LANG_C_H(EditPaste, GE, "&Einfügen", "Fügt den Inhalt der Zwischenablage an der aktuellen Cursorposition ein")
      LANG_C_H(EditPasteTransparent, EN, "P&aste transparently", "Pastes the contents of the clipboard transparently at the current cursor location")
      LANG_C_H(EditPasteTransparent, GE, "&Transparent einfügen", "Fügt den Inhalt der Zwischenablage transparent an der aktuellen Cursorposition ein")
      LANG_C_H(EditInvert, EN, "&Invert", "Inverts the selection")
      LANG_C_H(EditInvert, GE, "&Invertieren", "Inverts the selection")
      LANG_C_H(EditMirrorHorz, EN, "Mirror &horizontal", "Mirrors the selection in horizontal direction")
      LANG_C_H(EditMirrorHorz, GE, "Spiegeln &horizontal", "Spiegelt die Selektion in horizontaler Richtung")
      LANG_C_H(EditMirrorVert, EN, "Mirror &vertical", "Mirrors the selection in vertical direction")
      LANG_C_H(EditMirrorVert, GE, "Spiegeln &vertikal", "Spiegelt die Selektion in vertikaler Richtung")
      LANG_C_H(EditRotate, EN, "Rotat&e", "Rotates the square selection in clockwise direction")
      LANG_C_H(EditRotate, GE, "R&otieren", "Rotiert die quadratische Selektion im Uhrzeigersinn")
      LANG_C_H(EditCentralsym, EN, "Ma&ke central symmetric", "Tries to make the selection central symmetric")
      LANG_C_H(EditCentralsym, GE, "&Zentralsymmetrisch", "Versucht die Selektion zentralsymmetrisch zu machen")
      LANG_C_H(EditDelete, EN, "&Delete", "Deletes the selection")
      LANG_C_H(EditDelete, GE, "&Löschen", "Löscht die Selektion")
      LANG_C_H(MenuRoll, EN, "R&oll", "")
      LANG_C_H(MenuRoll, GE, "Rolle&n", "")
      LANG_C_H(RollUp, EN, "Roll &up", "Rolls the selection upwards")
      LANG_C_H(RollUp, GE, "Nach &oben", "Rollt die Selektion aufwärts")
      LANG_C_H(RollDown, EN, "Roll &down", "Rolls the selection downwards")
      LANG_C_H(RollDown, GE, "Nach &unten", "Rollt die Selektion abwärts")
      LANG_C_H(RollLeft, EN, "Roll &left", "Rolls the selection to the left")
      LANG_C_H(RollLeft, GE, "Nach &links", "Rollt die Selektion nach links")
      LANG_C_H(RollRight, EN, "Roll &right", "Rolls the selection to the right")
      LANG_C_H(RollRight, GE, "Nach &rechts", "Rollt die Selektion nach rechts")
      LANG_C_H(Steigung, EN, "&Slope", "")
      LANG_C_H(Steigung, GE, "&Steigung", "")
      LANG_C_H(SteigungInc, EN, "&Increase", "Increases the slope of the selection")
      LANG_C_H(SteigungInc, GE, "&Erhöhen", "Erhöht die Steigung der Selektion")
      LANG_C_H(SteigungDec, EN, "&Decrease", "Decreases the slope of the selection")
      LANG_C_H(SteigungDec, GE, "&Vermindern", "Vermindert die Steigung der Selektion")
      LANG_C_H(MenuMove, EN, "&Move", "")
      LANG_C_H(MenuMove, GE, "Ver&schieben", "")
      LANG_C_H(SchaftMoveUp, EN, "Harness &up", "Moves the selected harness up")
      LANG_C_H(SchaftMoveUp, GE, "Schaft nach &oben", "Verschiebt den aktuellen Schaft nach oben")
      LANG_C_H(SchaftMoveDown, EN, "Harness &down", "Moves the selected harness down")
      LANG_C_H(SchaftMoveDown, GE, "Schaft nach &unten", "Verschiebt den aktuellen Schaft nach unten")
      LANG_C_H(TrittMoveLeft, EN, "Treadle &left", "Moves the selected treadle left")
      LANG_C_H(TrittMoveLeft, GE, "Tritt nach &links", "Verschiebt den aktuellen Tritt nach links")
      LANG_C_H(TrittMoveRight, EN, "Treadle &right", "Moves the selected treadle right")
      LANG_C_H(TrittMoveRight, GE, "Tritt nach &rechts", "Verschiebt den aktuellen Tritt nach rechts")
      LANG_C_H(MenuInsert, EN, "I&nsert", "")
      LANG_C_H(MenuInsert, GE, "Ein&fügen", "")
      LANG_C_H(InsertSchaft, EN, "&Harness", "Inserts a harness at the current cursor position")
      LANG_C_H(InsertSchaft, GE, "&Schaft", "Fügt einen Schaft an der aktuellen Cursorposition ein")
      LANG_C_H(InsertTritt, EN, "&Treadle", "Inserts a treadle at the current cursor position")
      LANG_C_H(InsertTritt, GE, "&Tritt", "Fügt einen Tritt an der aktuellen Cursorposition ein")
      LANG_C_H(InsertKette, EN, "&End, Warp thread", "Inserts a warp thread at the current cursor position")
      LANG_C_H(InsertKette, GE, "&Kettfaden", "Fügt einen Kettfaden an der aktuellen Cursorposition ein")
      LANG_C_H(InsertSchuss, EN, "&Pick, Weft thread", "Inserts a weft thread at the current cursor position")
      LANG_C_H(InsertSchuss, GE, "Schuss&faden", "Fügt einen Schussfaden an der aktuellen Cursorposition ein")
      LANG_C_H(MenuDelete, EN, "De&lete", "")
      LANG_C_H(MenuDelete, GE, "Lös&chen", "")
      LANG_C_H(DeleteSchaft, EN, "&Harness", "Deletes the harness at the current cursor position")
      LANG_C_H(DeleteSchaft, GE, "&Schaft", "Löscht den Schaft an der aktuellen Cursorposition")
      LANG_C_H(DeleteTritt, EN, "&Treadle", "Deletes the treadle at the current cursor position")
      LANG_C_H(DeleteTritt, GE, "&Tritt", "Löscht den Tritt an der aktuellen Cursorposition")
      LANG_C_H(DeleteKette, EN, "&End, Warp thread", "Deletes the warp thread at the current cursor position")
      LANG_C_H(DeleteKette, GE, "&Kettfaden", "Löscht den Kettfaden an der aktuellen Cursorposition")
      LANG_C_H(DeleteSchuss, EN, "&Pick, Weft thread", "Deletes the weft thread at the current cursor position")
      LANG_C_H(DeleteSchuss, GE, "Schuss&faden", "Löscht den Schussfaden an der aktuellen Cursorposition")
      LANG_C_H(MenuLancierung, EN, "Lancee", "")
      LANG_C_H(MenuLancierung, GE, "&Lancierung", "")
      LANG_C_H(KettLancierung, EN, "&Warp lancee...", "Inserts warp threads in order to create a warp lancee")
      LANG_C_H(KettLancierung, GE, "&Kettlancierung...", "Fügt Kettfäden ein um eine Kettlancierung zu machen")
      LANG_C_H(SchussLancierung, EN, "W&eft lancee...", "Inserts weft threads in order to create a weft lancee")
      LANG_C_H(SchussLancierung, GE, "&Schusslancierung...", "Fügt Schussfäden ein um eine Schusslancierung zu machen")
      LANG_C_H(EditFillKoeper, EN, "T&will completion", "Complements the currently selected thread to a complete twill")
      LANG_C_H(EditFillKoeper, GE, "&Köper ergänzen", "Ergänzt den selektierten Faden zu einem vollständigen Köper")
      LANG_C_H(EditSwapside, EN, "Switch side", "Switches to the other side of the pattern")
      LANG_C_H(EditSwapside, GE, "Seite wechseln", "Wechselt auf die andere Seite des Musters")


      // Menu Ansicht
      LANG_C_H(MenuAnsicht, EN, "&View", "")
      LANG_C_H(MenuAnsicht, GE, "&Ansicht", "")
      LANG_C_H(ViewBlatteinzug, EN, "R&eed threading", "Toggles reed threading")
      LANG_C_H(ViewBlatteinzug, GE, "&Blatteinzug", "Blatteinzug sichtbar/unsichtbar")
      LANG_C_H(ViewFarbe, EN, "&Color", "Toggles color")
      LANG_C_H(ViewFarbe, GE, "&Farbe", "Farbe sichtbar/unsichtbar")
      LANG_C_H(ViewEinzug, EN, "&Threading", "Toggles threading")
      LANG_C_H(ViewEinzug, GE, "&Einzug", "Einzug sichtbar/unsichtbar")
      if (ViewSchlagpatrone->Checked) {
          LANG_C_H(ViewTrittfolge, EN, "Pegpl&an", "Toggles pegplan")
          LANG_C_H(ViewTrittfolge, GE, "Schlagpa&trone", "Schlagpatrone sichtbar/unsichtbar")
      } else {
          LANG_C_H(ViewTrittfolge, EN, "Tre&adling", "Toggles treadling")
          LANG_C_H(ViewTrittfolge, GE, "&Trittfolge", "Trittfolge sichtbar/unsichtbar")
      }
      LANG_C_H(ViewHlines, EN, "&Support lines", "Toggles support-lines")
      LANG_C_H(ViewHlines, GE, "&Hilfslinien", "Hilfslinien sichtbar/unsichtbar")
      LANG_C_H(ViewOnlyGewebe, EN, "&Only pattern", "Displays only the pattern")
      LANG_C_H(ViewOnlyGewebe, GE, "&Nur Bindung", "Zeigt nur die Bindung an")
      LANG_C_H(Gewebe, EN, "&View", "")
      LANG_C_H(Gewebe, GE, "&Ansicht", "")
      LANG_C_H(GewebeNone, EN, "&Invisible", "Suppresses the pattern")
      LANG_C_H(GewebeNone, GE, "&Unsichtbar", "Unterdrückt die Bindung")
      LANG_C_H(GewebeNormal, EN, "&Draft", "Draft mode")
      LANG_C_H(GewebeNormal, GE, "&Patrone", "Patronenmodus")
      LANG_C_H(GewebeFarbeffekt, EN, "&Color", "Color mode")
      LANG_C_H(GewebeFarbeffekt, GE, "&Farbeffekt", "Farbeffektmodus")
      LANG_C_H(GewebeSimulation, EN, "&Fabric", "Fabric mode")
      LANG_C_H(GewebeSimulation, GE, "&Gewebe", "Gewebesimulationsmodus")
      LANG_C_H(ViewZoomIn, EN, "&Zoom in", "Zoom in")
      LANG_C_H(ViewZoomIn, GE, "&Vergrössern", "Vergrössert die Ansicht")
      LANG_C_H(ViewZoomNormal, EN, "&Normal", "Sets magnification to default value")
      LANG_C_H(ViewZoomNormal, GE, "&Normal", "Stellt die Standardgrösse ein")
      LANG_C_H(ViewZoomOut, EN, "Zoo&m out", "Zoom out")
      LANG_C_H(ViewZoomOut, GE, "Ver&kleinern", "Verkleinert die Ansicht")
      LANG_C_H(ViewToolpalette, EN, "Too&lpalette", "Toggles the toolpalette (drawing mode)")
      LANG_C_H(ViewToolpalette, GE, "&Werkzeugpalette", "Werkzeugpalette sichtbar/unsichtbar (Zeichnenmodus)")
      LANG_C_H(ViewRedraw, EN, "Redraw", "Redraws everything")
      LANG_C_H(ViewRedraw, GE, "Neuzeichnen", "Zeichnet alles neu")
      LANG_C_H(Overview, EN, "Overv&iew", "Enters an overview-mode")
      LANG_C_H(Overview, GE, "Übe&rsicht", "Schaltet in einen Übersichtsmodus um")


      // Menu Einzug
      LANG_C_H(MenuEinzug, EN, "&Threading", "")
      LANG_C_H(MenuEinzug, GE, "&Einzug", "")
      LANG_C_H(EinzugAssistent, EN, "Treading wizard...", "")
      LANG_C_H(EinzugAssistent, GE, "Einzugassistent...", "")
      LANG_C_H(EzSpiegeln, EN, "&Mirror all", "Mirrors the threading in horizontal direction")
      LANG_C_H(EzSpiegeln, GE, "&Spiegeln", "Spiegelt den Einzug in horizontaler Richtung")
      LANG_C_H(ClearEinzug, EN, "&Delete", "Deletes the threading")
      LANG_C_H(ClearEinzug, GE, "&Löschen", "Löscht den Einzug")
      LANG_C_H(EzMinimalZ, EN, "Normal &rising", "Arranges the threading in a rising manner")
      LANG_C_H(EzMinimalZ, GE, "&Normal steigend", "Ordnet den Einzug steigend")
      LANG_C_H(EzMinimalS, EN, "Normal &falling", "Arranges the threading in a falling manner")
      LANG_C_H(EzMinimalS, GE, "Normal &fallend", "Ordnet den Einzug fallend an")
      LANG_C_H(EzGeradeZ, EN, "&Straight rising", "Arranges the threading straight rising")
      LANG_C_H(EzGeradeZ, GE, "&Gerade steigend", "Ordnet den Einzug gerade steigend an")
      LANG_C_H(EzGeradeS, EN, "S&traight falling", "Arranges the threading straight falling")
      LANG_C_H(EzGeradeS, GE, "G&erade fallend", "Ordnet den Einzug gerade fallend an")
      LANG_C_H(EzChorig2, EN, "&2 choirs", "Arranges the threading in a simple 2-choir scheme")
      LANG_C_H(EzChorig2, GE, "&2-chorig", "Ordnet den Einzug in einem einfachen Zweichorsystem an")
      LANG_C_H(EzChorig3, EN, "&3 choirs", "Arranges the threading in a simple 3-choir scheme")
      LANG_C_H(EzChorig3, GE, "&3-chorig", "Ordnet den Einzug in einem einfachen Dreichorsystem")
      LANG_C_H(EzBelassen, EN, "Fi&xed", "Tries to leave the threading as is")
      LANG_C_H(EzBelassen, GE, "Fi&xiert", "Versucht den Einzug so zu belassen wie er ist")
      LANG_C_H(EzFixiert, EN, "&User defined...", "Arranges the threading according to a user-supplied template")
      LANG_C_H(EzFixiert, GE, "&Benutzerdefiniert...", "Ordnet den Einzug gemäss einem vom Benutzer vorgegebenen Schema an")
      LANG_C_H(CopyEinzugTrittfolge, EN, "&Copy from treadling", "Copies the treadling into the threading")
      LANG_C_H(CopyEinzugTrittfolge, GE, "&Kopieren von Trittfolge", "Kopiert die Trittfolge in den Einzug")


      // Menu Trittfolge
      LANG_C_H(MenuTrittfolge, EN, "Tre&adling", "")
      LANG_C_H(MenuTrittfolge, GE, "&Trittfolge", "")
      LANG_C_H(TfSpiegeln, EN, "&Mirror", "Mirrors the treadling in vertical direction")
      LANG_C_H(TfSpiegeln, GE, "&Spiegeln", "Spiegelt die Trittfolge in vertikaler Richtung")
      LANG_C_H(ClearTrittfolge, EN, "&Delete", "Deletes the treadling")
      LANG_C_H(ClearTrittfolge, GE, "&Löschen", "Löscht die Trittfolge")
      LANG_C_H(TfMinimalZ, EN, "Normal &rising", "Arranges the treadling rising")
      LANG_C_H(TfMinimalZ, GE, "&Normal steigend", "Ordnet die Trittfolge steigend an")
      LANG_C_H(TfMinimalS, EN, "Normal &falling", "Arranges the treadling falling")
      LANG_C_H(TfMinimalS, GE, "Normal &fallend", "Ordnet die Trittfolge fallend an")
      LANG_C_H(TfGeradeZ, EN, "&Straight rising", "Arranges the treadling straight rising")
      LANG_C_H(TfGeradeZ, GE, "&Gerade steigend", "Ordnet die Trittfolge gerade steigend an")
      LANG_C_H(TfGeradeS, EN, "S&traight falling", "Arranges the treadling straight falling")
      LANG_C_H(TfGeradeS, GE, "G&erade fallend", "Ordnet die Trittfolge gerade fallend an")
      LANG_C_H(TfGesprungen, EN, "Cr&ossed", "Arranges the treadling crossed")
      LANG_C_H(TfGesprungen, GE, "Gesp&rungen", "Ordnet die Trittfolge gesprungen an")
      LANG_C_H(TfBelassen, EN, "Fi&xed", "Tries to leave the treadling as is")
      LANG_C_H(TfBelassen, GE, "Fi&xiert", "Versucht die Trittfolge so zu belassen wie sie ist")
      LANG_C_H(CopyTrittfolgeEinzug, EN, "C&opy from threading", "Copies the threading into the treadling")
      LANG_C_H(CopyTrittfolgeEinzug, GE, "&Kopieren von Einzug", "Kopiert den Einzug in die Trittfolge")


      // Menu Schlagpatrone
      LANG_C_H(MenuSchlagpatrone, EN, "&Pegplan", "")
      LANG_C_H(MenuSchlagpatrone, GE, "&Schlagpatrone", "")
      LANG_C_H(SpInvert, EN, "&Invert", "Inverts the pegplan")
      LANG_C_H(SpInvert, GE, "&Invertieren", "Invertiert die gesamte Schlagpatrone")
      LANG_C_H(ClearSchlagpatrone, EN, "&Delete", "Deletes the pegplan")
      LANG_C_H(ClearSchlagpatrone, GE, "&Löschen", "Löscht die Schlagpatrone")
      LANG_C_H(SpSpiegeln, EN, "&Mirror", "Mirrors the pegplan in vertical direction")
      LANG_C_H(SpSpiegeln, GE, "&Spiegeln", "Spiegelt die Schlagpatrone in vertikaler Richtung")


      // Menu Aufknuepfung
      LANG_C_H(MenuAufknuepfung, EN, "Tie-&up", "")
      LANG_C_H(MenuAufknuepfung, GE, "A&ufknüpfung", "")
      LANG_C_H(AufInvert, EN, "&Invert", "Inverts the tie-up")
      LANG_C_H(AufInvert, GE, "&Invertieren", "Invertiert die Aufknüpfung")
      LANG_C_H(ClearAufknuepfung, EN, "&Delete", "Deletes the tie-up")
      LANG_C_H(ClearAufknuepfung, GE, "&Löschen", "Löscht die Aufknüpfung")
      LANG_C_H(AufRollen, EN, "&Roll", "")
      LANG_C_H(AufRollen, GE, "&Rollen", "")
      LANG_C_H(AufRollUp, EN, "&Up", "Rolls the tie-up up")
      LANG_C_H(AufRollUp, GE, "Nach &oben", "Rollt die Aufknüpfung nach oben")
      LANG_C_H(AufRollDown, EN, "&Down", "Rolls the tie-up down")
      LANG_C_H(AufRollDown, GE, "Nach &unten", "Rollt die Aufknüpfung nach unten")
      LANG_C_H(AufRollLeft, EN, "&Left", "Rolls the tie-up left")
      LANG_C_H(AufRollLeft, GE, "Nach &links", "Rollt die Aufknüpfung nach links")
      LANG_C_H(AufRollRight, EN, "&Right", "Rolls the tie-up right")
      LANG_C_H(AufRollRight, GE, "Nach &rechts", "Rollt die Aufknüpfung nach rechts")
      LANG_C_H(AufSteigung, EN, "&Slope", "")
      LANG_C_H(AufSteigung, GE, "&Steigung", "")
      LANG_C_H(AufSteigungInc, EN, "&Increase", "Increases the slope of the tie-up")
      LANG_C_H(AufSteigungInc, GE, "&Erhöhen", "Erhöht die Steigung der Aufknüpfung")
      LANG_C_H(AufSteigungDec, EN, "&Decrease", "Decreases the slope of the tie-up")
      LANG_C_H(AufSteigungDec, GE, "&Vermindern", "Vermindert die Steigung der Aufknüpfung")
      LANG_C_H(AufZentralsymm, EN, "Ma&ke central symmetric", "Tries to make the tie-up central symmetric")
      LANG_C_H(AufZentralsymm, GE, "&Zentralsymmetrisch", "Versucht die Aufknüpfung zentralsymmetrisch zu machen")


      // Menu Einfügen
      LANG_C_H(MenuEinfuegen, EN, "&Insert", "")
      LANG_C_H(MenuEinfuegen, GE, "Ei&nfügen", "")
      LANG_C_H(Atlas, EN, "&Satin", "")
      LANG_C_H(Atlas, GE, "&Atlas", "")
      LANG_C_H(Atlas5, EN, "Satin &5", "")
      LANG_C_H(Atlas5, GE, "Atlas &5", "")
      LANG_C_H(Atlas6, EN, "Satin &6", "")
      LANG_C_H(Atlas6, GE, "Atlas &6", "")
      LANG_C_H(Atlas7, EN, "Satin &7", "")
      LANG_C_H(Atlas7, GE, "Atlas &7", "")
      LANG_C_H(Atlas8, EN, "Satin &8", "")
      LANG_C_H(Atlas8, GE, "Atlas &8", "")
      LANG_C_H(Atlas9, EN, "Satin &9", "")
      LANG_C_H(Atlas9, GE, "Atlas &9", "")
      LANG_C_H(Atlas10, EN, "Satin &10", "")
      LANG_C_H(Atlas10, GE, "Atlas &10", "")
      LANG_C_H(Koeper, EN, "&Twill", "")
      LANG_C_H(Koeper, GE, "&Köper", "")
      LANG_C_H(gleichseitig, EN, "&Balanced", "")
      LANG_C_H(gleichseitig, GE, "&Gleichseitig", "")
      LANG_C_H(Kettkoeper, EN, "&Warp sided", "")
      LANG_C_H(Kettkoeper, GE, "&Kettseitig", "")
      LANG_C_H(Koeper2_1, EN, "Twill 2/1", "")
      LANG_C_H(Koeper2_1, GE, "Köper 2/1", "")
      LANG_C_H(Koeper3_1, EN, "Twill 3/1", "")
      LANG_C_H(Koeper3_1, GE, "Köper 3/1", "")
      LANG_C_H(Koeper4_1, EN, "Twill 4/1", "")
      LANG_C_H(Koeper4_1, GE, "Köper 4/1", "")
      LANG_C_H(Koeper5_1, EN, "Twill 5/1", "")
      LANG_C_H(Koeper5_1, GE, "Köper 5/1", "")
      LANG_C_H(Koeper3_2, EN, "Twill 3/2", "")
      LANG_C_H(Koeper3_2, GE, "Köper 3/2", "")
      LANG_C_H(Koeper4_2, EN, "Twill 4/2", "")
      LANG_C_H(Koeper4_2, GE, "Köper 4/2", "")
      LANG_C_H(Koeper5_2, EN, "Twill 5/2", "")
      LANG_C_H(Koeper5_2, GE, "Köper 5/2", "")
      LANG_C_H(Koeper4_3, EN, "Twill 4/3", "")
      LANG_C_H(Koeper4_3, GE, "Köper 4/3", "")
      LANG_C_H(Koeper5_3, EN, "Twill 5/3", "")
      LANG_C_H(Koeper5_3, GE, "Köper 5/3", "")
      LANG_C_H(Koeper2_2, EN, "Twill 2/2", "")
      LANG_C_H(Koeper2_2, GE, "Köper 2/2", "")
      LANG_C_H(Koeper3_3, EN, "Twill 3/3", "")
      LANG_C_H(Koeper3_3, GE, "Köper 3/3", "")
      LANG_C_H(Koeper4_4, EN, "Twill 4/4", "")
      LANG_C_H(Koeper4_4, GE, "Köper 4/4", "")
      LANG_C_H(Koeper5_5, EN, "Twill 5/5", "")
      LANG_C_H(Koeper5_5, GE, "Köper 5/5", "")
      LANG_C_H(MenuWeitere, EN, "&Additional", "")
      LANG_C_H(MenuWeitere, GE, "&Weitere", "")
      LANG_C_H(Userdef1, EN, "User defined 1", "")
      LANG_C_H(Userdef1, GE, "Benutzerdefiniert 1", "")
      LANG_C_H(Userdef2, EN, "User defined 2", "")
      LANG_C_H(Userdef2, GE, "Benutzerdefiniert 2", "")
      LANG_C_H(Userdef3, EN, "User defined 3", "")
      LANG_C_H(Userdef3, GE, "Benutzerdefiniert 3", "")
      LANG_C_H(Userdef4, EN, "User defined 4", "")
      LANG_C_H(Userdef4, GE, "Benutzerdefiniert 4", "")
      LANG_C_H(Userdef5, EN, "User defined 5", "")
      LANG_C_H(Userdef5, GE, "Benutzerdefiniert 5", "")
      LANG_C_H(Userdef6, EN, "User defined 6", "")
      LANG_C_H(Userdef6, GE, "Benutzerdefiniert 6", "")
      LANG_C_H(Userdef7, EN, "User defined 7", "")
      LANG_C_H(Userdef7, GE, "Benutzerdefiniert 7", "")
      LANG_C_H(Userdef8, EN, "User defined 8", "")
      LANG_C_H(Userdef8, GE, "Benutzerdefiniert 8", "")
      LANG_C_H(Userdef9, EN, "User defined 9", "")
      LANG_C_H(Userdef9, GE, "Benutzerdefiniert 9", "")
      LANG_C_H(Userdef10, EN, "User defined 10", "")
      LANG_C_H(Userdef10, GE, "Benutzerdefiniert 10", "")
      LANG_C_H(AdminUserdef, EN, "A&dministration", "")
      LANG_C_H(AdminUserdef, GE, "&Verwaltung", "")
      LANG_C_H(UserdefAdd, EN, "&Add current pattern...", "")
      LANG_C_H(UserdefAdd, GE, "&Muster hinzufügen...", "")
      LANG_C_H(UserdefAddSel, EN, "Add &selection...", "")
      LANG_C_H(UserdefAddSel, GE, "&Selektion hinzufügen...", "")
      LANG_C_H(UserdefRemove, EN, "&Remove...", "")
      LANG_C_H(UserdefRemove, GE, "&Löschen...", "")

      // Menu Rapport
      LANG_C_H(MenuRapport, EN, "&Repeat", "")
      LANG_C_H(MenuRapport, GE, "&Rapport", "")
      LANG_C_H(RappViewRapport, EN, "&Repeat visible", "Toggles repeat")
      LANG_C_H(RappViewRapport, GE, "&Rapport sichtbar", "Rapport sichtbar/unsichtbar")
      LANG_C_H(RappRapportieren, EN, "R&epeat...", "Repeats the pattern")
      LANG_C_H(RappRapportieren, GE, "R&apportieren...", "Rapportiert das Muster")
      LANG_C_H(RappReduzieren, EN, "Re&duce", "Reduces the pattern to 1x1 repeat")
      LANG_C_H(RappReduzieren, GE, "Re&duzieren", "Reduziert das Muster auf einen Rapport")
      if (RappOverride->Checked) {
          RappOverride->Caption = RECALCRAPPORT;
          RappOverride->Hint = LANG_STR("Recalcs the repeat", "Berechnet den Rapport neu");
      } else {
          RappOverride->Caption = SETRAPPORTTOSELECTION;
          RappOverride->Hint = LANG_STR("Defines the repeat to the selection", "Definiert den Rapport als die Selektion");
      }
      LANG_C_H(Inverserepeat, EN, "&Invert repeat colors", "")
      LANG_C_H(Inverserepeat, GE, "Rapportfarben &umgekehrt", "")


      // Menu Farbe
      LANG_C_H(MenuFarbe, EN, "&Color", "")
      LANG_C_H(MenuFarbe, GE, "&Farbe", "")
      LANG_C_H(ViewFarbpalette, EN, "&Palette", "Toggles color palette")
      LANG_C_H(ViewFarbpalette, GE, "&Palette", "Farbpalette sichtbar/unsichtbar")
      LANG_C_H(DefineColors, EN, "&Edit colors...", "Edits the colors of the palette")
      LANG_C_H(DefineColors, GE, "&Farben bearbeiten...", "Bearbeitet die Paletten-Farben")
      LANG_C_H(Farbverlauf, EN, "Color &blending...", "Creates a color blending")
      LANG_C_H(Farbverlauf, GE, "Farb&verlauf...", "Erstellt einen Farbverlauf")
      LANG_C_H(SetKettfarbe, EN, "Set &warp color...", "Sets the warp color")
      LANG_C_H(SetKettfarbe, GE, "&Kettfarbe setzen...", "Setzt die Kettfarbe")
      LANG_C_H(SetSchussfarbe, EN, "Set we&ft color...", "Sets the weft color")
      LANG_C_H(SetSchussfarbe, GE, "&Schussfarbe setzen...", "Setzt die Schussfarbe")
      LANG_C_H(ReplaceColor, EN, "&Replace color...", "Replaces the color at the cursor position globally")
      LANG_C_H(ReplaceColor, GE, "Farbe e&rsetzen...", "Ersetzt die Farbe an der Cursorposition global")
      LANG_C_H(KettfarbenWieSchussfarben, EN, "Warp colors as weft colors", "")
      LANG_C_H(KettfarbenWieSchussfarben, GE, "Kett- wie Schussfarben", "")
      LANG_C_H(SchussfarbenWieKettfarben, EN, "Weft colors as warp colors", "")
      LANG_C_H(SchussfarbenWieKettfarben, GE, "Schuss- wie Kettfarben", "")
      LANG_C_H(SwitchColors, EN, "&Switch colors", "Switches warp and weft colors")
      LANG_C_H(SwitchColors, GE, "F&arben vertauschen", "Vertauscht Kett- und Schussfarben")


      // Menu Bereiche
      LANG_C_H(MenuBereich, EN, "Ra&nge", "")
      LANG_C_H(MenuBereich, GE, "Bere&iche", "")
      LANG_C_H(ImportBitmap, EN, "&Import bitmap...", "Imports a bitmap")
      LANG_C_H(ImportBitmap, GE, "&Bild importieren...", "Importiert ein Bild")
      LANG_C_H(AktuellerBereich1, EN, "&Current range", "")
      LANG_C_H(AktuellerBereich1, GE, "&Aktueller Bereich", "")
      LANG_C_H(Range1, EN, "Range &1", "Activates range 1")
      LANG_C_H(Range1, GE, "Bereich &1", "Aktiviert Bereich 1")
      LANG_C_H(Range2, EN, "Range &2", "Activates range 2")
      LANG_C_H(Range2, GE, "Bereich &2", "Aktiviert Bereich 2")
      LANG_C_H(Range3, EN, "Range &3", "Activates range 3")
      LANG_C_H(Range3, GE, "Bereich &3", "Aktiviert Bereich 3")
      LANG_C_H(Range4, EN, "Range &4", "Activates range 4")
      LANG_C_H(Range4, GE, "Bereich &4", "Aktiviert Bereich 4")
      LANG_C_H(Range5, EN, "Range &5", "Activates range 5")
      LANG_C_H(Range5, GE, "Bereich &5", "Aktiviert Bereich 5")
      LANG_C_H(Range6, EN, "Range &6", "Activates range 6")
      LANG_C_H(Range6, GE, "Bereich &6", "Aktiviert Bereich 6")
      LANG_C_H(Range7, EN, "Range &7", "Activates range 7")
      LANG_C_H(Range7, GE, "Bereich &7", "Aktiviert Bereich 7")
      LANG_C_H(Range8, EN, "Range &8", "Activates range 8")
      LANG_C_H(Range8, GE, "Bereich &8", "Aktiviert Bereich 8")
      LANG_C_H(Range9, EN, "Range &9", "Activates range 9")
      LANG_C_H(Range9, GE, "Bereich &9", "Aktiviert Bereich 9")
      LANG_C_H(RangeAushebung, EN, "&Lift out", "Activates lift out range")
      LANG_C_H(RangeAushebung, GE, "&Aushebung", "Aktiviert Aushebungs-Bereich")
      LANG_C_H(RangeAnbindung, EN, "&Binding", "Activates binding point range")
      LANG_C_H(RangeAnbindung, GE, "A&nbindung", "Aktiviert Anbindungs-Bereich")
      LANG_C_H(RangeAbbindung, EN, "&Unbinding", "Activates unbinding point range")
      LANG_C_H(RangeAbbindung, GE, "A&bbindung", "Aktiviert Abbindungs-Bereich")
      LANG_C_H(EditBlockmuster, EN, "&Block substitution...", "Creates a block substitution")
      LANG_C_H(EditBlockmuster, GE, "&Blockmusterung...", "Erstellt eine Blockmusterung")
      LANG_C_H(RangePatterns, EN, "&Range substitution...", "Creates a range substitution")
      LANG_C_H(RangePatterns, GE, "B&ereichsmusterung...", "Erstellt eine Bereichsmusterung")


      // Menu Extras
      LANG_C_H(MenuExtras, EN, "E&xtras", "")
      LANG_C_H(MenuExtras, GE, "E&xtras", "")
      LANG_C_H(OptionsLockGewebe, EN, "Pattern &locked", "Locks the pattern; No changes can be made anymore")
      LANG_C_H(OptionsLockGewebe, GE, "&Bindung gesperrt", "Sperrt die Bindung; Keine Änderungen mehr möglich")
      LANG_C_H(CursorMenu, EN, "&Cursor", "")
      LANG_C_H(CursorMenu, GE, "&Cursor", "")
      LANG_C_H(CursorLocked, EN, "&Contained", "Restricts the cursor position within the repeat")
      LANG_C_H(CursorLocked, GE, "&In Rapport", "Beschränkt die Cursorposition auf den Rapport")
      LANG_C_H(EditCursordirection, EN, "&Movement...", "Configures the automatic cursor movement")
      LANG_C_H(EditCursordirection, GE, "&Bewegung...", "Konfiguriert die automatische Cursorbewegung")
      LANG_C_H(CursorGoto, EN, "&Go to...", "Sets the cursor to a specific field")
      LANG_C_H(CursorGoto, GE, "&Gehe zu...", "Setzt den Cursor in ein spezifisches Feld")
      LANG_C_H(EinstellVerhaeltnis, EN, "&Weft/warp-ratio...", "Sets the weft/warp-ratio")
      LANG_C_H(EinstellVerhaeltnis, GE, "Schuss/&Kett-Verhältnis...", "Setzt das Schuss/Kett-Verhältnis")
      LANG_C_H(ViewSchlagpatrone, EN, "&Pegplan", "Toggles pegplan mode")
      LANG_C_H(ViewSchlagpatrone, GE, "&Schlagpatrone", "Wechselt zwischen Schlagpatrone und Aufknüpfung/Trittfolge")
      LANG_C_H(Weave, EN, "&Weave", "Switches into the weaving mode")
      LANG_C_H(Weave, GE, "&Weben", "Wechselt in den Weben-Modus")
      LANG_C_H(ViewInfos, EN, "&Information...", "Displays information about the current pattern")
      LANG_C_H(ViewInfos, GE, "&Informationen...", "Zeigt Informationen über das aktuelle Muster an")
      LANG_C_H(Basestyle, EN, "&Base settings", "")
      LANG_C_H(Basestyle, GE, "&Grundeinstellung", "")
      LANG_C_H(OptAmerican, EN, "&American", "Activates the settings commonly used in the united states")
      LANG_C_H(OptAmerican, GE, "&Amerikanisch", "Aktiviert die Einstellungen, die gewöhnlich in den USA verwendet werden")
      LANG_C_H(OptSkandinavisch, EN, "&Scandinavian", "Activates the settings commonly used in the scandinavian region")
      LANG_C_H(OptSkandinavisch, GE, "&Skandinavisch", "Aktiviert die Einstellungen, die gewöhnlich in der skandinavischen Region verwendet werden")
      LANG_C_H(OptSwiss, EN, "&German/Swiss", "Activates the settings commonly used in Germany and Switzerland")
      LANG_C_H(OptSwiss, GE, "&Deutsch/Schweizerisch", "Aktiviert die Einstellungen, die gewöhnlich in Deutschland und der Schweiz verwendet werden")
      LANG_C_H(MenuOptions, EN, "&Options", "")
      LANG_C_H(MenuOptions, GE, "&Optionen", "")
      LANG_C_H(XOptions, EN, "&For this pattern...", "Edits options for this pattern")
      LANG_C_H(XOptions, GE, "&Für dieses Muster...", "Bearbeitet Optionen für dieses Muster")
      LANG_C_H(XOptionsGlobal, EN, "&Global...", "Edits options for this and all new patterns")
      LANG_C_H(XOptionsGlobal, GE, "&Global...", "Bearbeitet Optionen für dieses und alle neuen Muster")
      LANG_C_H(OptEnvironment, EN, "&Environment...", "Edits environment options")
      LANG_C_H(OptEnvironment, GE, "&Umgebung...", "Bearbeitet Umgebungsoptionen")


      // Menu ?
      LANG_C_H(MenuHelp, EN, "&?", "")
      LANG_C_H(MenuHelp, GE, "&?", "")
      LANG_C_H(HelpBsoftOnline, EN, "&Brunold Software Online", "Brings you to the website of Brunold Software")
      LANG_C_H(HelpBsoftOnline, GE, "&Brunold Software Online", "Bringt Sie auf die Website von Brunold Software")
      LANG_C_H(HelpTechinfo, EN, "&Technical information...", "Displays technical information about DB-WEAVE, your computer and the operating system used")
      LANG_C_H(HelpTechinfo, GE, "&Technische Informationen...", "Zeigt technische Informationen über DB-WEAVE, Ihren Computer und das verwendete Betriebssystem an")
      LANG_C_H(HelpAbout, EN, "About &DB-WEAVE...", "Displays information about DB-WEAVE")
      LANG_C_H(HelpAbout, GE, "Über &DB-WEAVE...", "Zeigt Informationen über DB-WEAVE an")


    // Popupmenüs

      // Zeige-Popup
      LANG_C_H(PopupCancel, EN, "Cancel", "Leaves this menu")
      LANG_C_H(PopupCancel, GE, "Abbrechen", "Verlässt dieses Menü")
      LANG_C_H(ViewBlatteinzugPopup, EN, "Reed threading", "Toggles reed threading")
      LANG_C_H(ViewBlatteinzugPopup, GE, "Blatteinzug", "Blatteinzug sichtbar/unsichtbar")
      LANG_C_H(ViewFarbePopup, EN, "Color", "Toggles color")
      LANG_C_H(ViewFarbePopup, GE, "Farbe", "Farbe sichtbar/unsichtbar")
      LANG_C_H(ViewEinzugPopup, EN, "Threading", "Toggles threading")
      LANG_C_H(ViewEinzugPopup, GE, "Einzug", "Einzug sichtbar/unsichtbar")
      if (ViewSchlagpatrone->Checked) {
          LANG_C_H(ViewTrittfolgePopup, EN, "Pegplan", "Toggles pegplan")
          LANG_C_H(ViewTrittfolgePopup, GE, "Schlagpatrone", "Schlagpatrone sichtbar/unsichtbar")
      } else {
          LANG_C_H(ViewTrittfolgePopup, EN, "Treadling", "Toggles treadling")
          LANG_C_H(ViewTrittfolgePopup, GE, "Trittfolge", "Trittfolge sichtbar/unsichtbar")
      }
      LANG_C_H(PastePopup, EN, "Paste", "Pastes the contents of the clipboard at the current cursor position")
      LANG_C_H(PastePopup, GE, "Einfügen", "Fügt den Inhalt der Zwischenablage an der aktuellen Cursorposition ein")
      LANG_C_H(PasteTransparentlyPopup, EN, "Paste transparently", "Transparently pastes the contents of the clipboard at the current cursor position")
      LANG_C_H(PasteTransparentlyPopup, GE, "Transparent Einfügen", "Fügt den Inhalt der Zwischenablage an der aktuellen Cursorposition transparent ein")
      LANG_C_H(ViewZoomInPopup, EN, "Zoom in", "Zoom in")
      LANG_C_H(ViewZoomInPopup, GE, "Vergrössern", "Vergrössert die Ansicht")
      LANG_C_H(ViewZoomOutPopup, EN, "Zoom out", "Zoom out")
      LANG_C_H(ViewZoomOutPopup, GE, "Verkleinern", "Verkleinert die Ansicht")
      LANG_C_H(ViewmodePopup, EN, "View", "")
      LANG_C_H(ViewmodePopup, GE, "Ansicht", "")
      LANG_C_H(GewebeNonePopup, EN, "Invisible", "Suppresses the pattern")
      LANG_C_H(GewebeNonePopup, GE, "Unsichtbar", "Unterdrückt die Bindung")
      LANG_C_H(GewebeNormalPopup, EN, "Draft", "Draft mode")
      LANG_C_H(GewebeNormalPopup, GE, "Patrone", "Patronenmodus")
      LANG_C_H(GewebeFarbeffektPopup, EN, "Color", "Color mode")
      LANG_C_H(GewebeFarbeffektPopup, GE, "Farbeffekt", "Farbeffektmodus")
      LANG_C_H(GewebeSimulationPopup, EN, "Fabric", "Fabric mode")
      LANG_C_H(GewebeSimulationPopup, GE, "Gewebe", "Gewebesimulationsmodus")

      // Selektion-Popup
      LANG_C_H(Popup1Cancel, EN, "Cancel", "Leaves this menu")
      LANG_C_H(Popup1Cancel, GE, "Abbrechen", "Verlässt dieses Menü")
      LANG_C_H(Popup1Cut, EN, "Cut", "Cuts the selection to the clipboard")
      LANG_C_H(Popup1Cut, GE, "Ausschneiden", "Schneidet die Selektion aus und speichert sie in der Zwischenablage")
      LANG_C_H(Popup1Copy, EN, "Copy", "Copies the selection to the clipboard")
      LANG_C_H(Popup1Copy, GE, "Kopieren", "Kopiert die Selektion in die Zwischenablage")
      LANG_C_H(Paste1Popup, EN, "Paste", "Pastes the contents of the clipboard at the current cursor position")
      LANG_C_H(Paste1Popup, GE, "Einfügen", "Fügt den Inhalt der Zwischenablage an der aktuellen Cursorposition ein")
      LANG_C_H(Paste1TransparentlyPopup, EN, "Paste transparently", "Pastes the contents of the clipboard transparently at the current cursor position")
      LANG_C_H(Paste1TransparentlyPopup, GE, "Transparent einfügen", "Fügt den Inhalt der Zwischenablage an der aktuellen Cursorposition transparent ein")
      LANG_C_H(Popup1Invert, EN, "Invert", "Inverts the selection")
      LANG_C_H(Popup1Invert, GE, "Invertieren", "Invertiert die Selektion")
      LANG_C_H(Popup1MirrorH, EN, "Mirror horizontal", "Mirrors the selection in horizontal direction")
      LANG_C_H(Popup1MirrorH, GE, "Spiegeln horizontal", "Spiegelt die Selektion in horizontaler Richtung")
      LANG_C_H(Popup1MirrorV, EN, "Mirror vertical", "Mirrors the selection in vertical direction")
      LANG_C_H(Popup1MirrorV, GE, "Spiegeln vertikal", "Spiegelt die Selektion in vertikaler Richtung")
      LANG_C_H(Popup1Rotate, EN, "Rotate", "Rotates the square selection in clockwise direction")
      LANG_C_H(Popup1Rotate, GE, "Rotieren", "Rotiert die quadratische Selektion im Uhrzeigersinn")
      LANG_C_H(Popup1Centralsym, EN, "Make central symmetric", "Tries to make the selection central symmetric")
      LANG_C_H(Popup1Centralsym, GE, "Zentralsymmetrisch", "Versucht, die Selektion zentralsymmetrisch zu machen")
      LANG_C_H(Popup1Delete, EN, "Delete", "Deletes the selection")
      LANG_C_H(Popup1Delete, GE, "Löschen", "Löscht die Selektion")
      LANG_C_H(Popup1Rollen, EN, "Roll", "")
      LANG_C_H(Popup1Rollen, GE, "Rollen", "")
      LANG_C_H(Popup1RollUp, EN, "Up", "Rolls the selection up")
      LANG_C_H(Popup1RollUp, GE, "Nach oben", "Rollt die Selektion nach oben")
      LANG_C_H(Popup1RollDown, EN, "Down", "Rolls the selection Down")
      LANG_C_H(Popup1RollDown, GE, "Nach unten", "Rollt die Selektion nach unten")
      LANG_C_H(Popup1RollLeft, EN, "Left", "Rolls the selection to the left")
      LANG_C_H(Popup1RollLeft, GE, "Nach links", "Rollt die Selektion nach links")
      LANG_C_H(Popup1RollRight, EN, "Right", "Rolls the selection to the right")
      LANG_C_H(Popup1RollRight, GE, "Nach rechts", "Rollt die Selektion nach rechts")

      // Range-Popup
      LANG_C_H(PopupRangeCancel, EN, "Cancel", "")
      LANG_C_H(PopupRangeCancel, GE, "Abbrechen", "")
      LANG_C_H(PopupRange1, EN, "Range 1", "")
      LANG_C_H(PopupRange1, GE, "Bereich 1", "")
      LANG_C_H(PopupRange2, EN, "Range 2", "")
      LANG_C_H(PopupRange2, GE, "Bereich 2", "")
      LANG_C_H(PopupRange3, EN, "Range 3", "")
      LANG_C_H(PopupRange3, GE, "Bereich 3", "")
      LANG_C_H(PopupRange4, EN, "Range 4", "")
      LANG_C_H(PopupRange4, GE, "Bereich 4", "")
      LANG_C_H(PopupRange5, EN, "Range 5", "")
      LANG_C_H(PopupRange5, GE, "Bereich 5", "")
      LANG_C_H(PopupRange6, EN, "Range 6", "")
      LANG_C_H(PopupRange6, GE, "Bereich 6", "")
      LANG_C_H(PopupRange7, EN, "Range 7", "")
      LANG_C_H(PopupRange7, GE, "Bereich 7", "")
      LANG_C_H(PopupRange8, EN, "Range 8", "")
      LANG_C_H(PopupRange8, GE, "Bereich 8", "")
      LANG_C_H(PopupRange9, EN, "Range 9", "")
      LANG_C_H(PopupRange9, GE, "Bereich 9", "")
      LANG_C_H(PopupRangeLiftout, EN, "Lift out", "")
      LANG_C_H(PopupRangeLiftout, GE, "Aushebung", "")
      LANG_C_H(PopupRangeBinding, EN, "Binding", "")
      LANG_C_H(PopupRangeBinding, GE, "Anbindung", "")
      LANG_C_H(PopupRangeUnbinding, EN, "Unbinding", "")
      LANG_C_H(PopupRangeUnbinding, GE, "Abbindung", "")

    // Toolbar

    LANG_C_H(SBFileNew, EN, "", "New|Creates a new pattern")
    LANG_C_H(SBFileNew, GE, "", "Neu|Erstellt ein neues Muster")

    LANG_C_H(SBFileOpen, EN, "", "Open|Opens a pattern")
    LANG_C_H(SBFileOpen, GE, "", "Öffnen|Öffnet ein Muster")

    LANG_C_H(SBSave, EN, "", "Save|Saves the pattern")
    LANG_C_H(SBSave, GE, "", "Speichern|Speichert das Muster")

    LANG_C_H(SBPreview, EN, "", "Print preview|Shows how the pattern will be printed")
    LANG_C_H(SBPreview, GE, "", "Druckvorschau|Zeit wie das Muster gedruckt wird")

    LANG_C_H(SBFilePrint, EN, "", "Print|Prints the pattern")
    LANG_C_H(SBFilePrint, GE, "", "Drucken|Druckt das Muster")

    LANG_C_H(SBUndo, EN, "", "Undo|Undoes the last change")
    LANG_C_H(SBUndo, GE, "", "Rückgängig|Macht die letzte Änderung rückgängig")

    LANG_C_H(SBRedo, EN, "", "Redo|Redoes the last undone change")
    LANG_C_H(SBRedo, GE, "", "Wiederholen|Macht die letzte rückgängig gemachte Änderung")

    LANG_C_H(SBEditCut, EN, "", "Cut|Cuts the selection to the clipboard")
    LANG_C_H(SBEditCut, GE, "", "Ausschneiden|Schneidet die Selektion in die Zwischenablage aus")

    LANG_C_H(SBEditCopy, EN, "", "Copy|Copies the seleciton to the clipboard")
    LANG_C_H(SBEditCopy, GE, "", "Kopieren|Kopiert die Selektion in die Zwischenablage")

    LANG_C_H(SBEditPaste, EN, "", "Paste|Pastes the contents of the clipboard at the current cursor location")
    LANG_C_H(SBEditPaste, GE, "", "Einfügen|Fügt den Inhalt der Zwischenablage an der aktuellen Cursorposition ein")

    LANG_C_H(SBZoomIn, EN, "", "Zoom in|Zoom in")
    LANG_C_H(SBZoomIn, GE, "", "Vergrössern|Vergrössert die Ansicht")

    LANG_C_H(SBZoomOut, EN, "", "Zoom out|Zoom out")
    LANG_C_H(SBZoomOut, GE, "", "Verkleinern|Verkleinert die Ansicht")

    LANG_C_H(SBMoveUp, EN, "", "Move up|Move the shaft upwards")
    LANG_C_H(SBMoveUp, GE, "", "Nach oben|Bewegt den Schaft nach oben")

    LANG_C_H(SBMoveDown, EN, "", "Move down|Moves the shaft downwards")
    LANG_C_H(SBMoveDown, GE, "", "Nach unten|Bewegt den Schaft nach unten")

    LANG_C_H(SBMoveLeft, EN, "", "Move left|Moves the treadle to the left")
    LANG_C_H(SBMoveLeft, GE, "", "Nach links|Bewegt den Tritt nach links")

    LANG_C_H(SBMoveRight, EN, "", "Move right|Moves the treadle to the right")
    LANG_C_H(SBMoveRight, GE, "", "Nach rechts|Bewegt den Tritt nach rechts")

    LANG_C_H(SBInvert, EN, "", "Invert|Inverts the selection")
    LANG_C_H(SBInvert, GE, "", "Invertieren|Invertiert die Selektion")

    LANG_C_H(SBMirrorH, EN, "", "Mirror horizontal|Mirrors the selection in horizontal direction")
    LANG_C_H(SBMirrorH, GE, "", "Spiegeln horizontal|Spiegelt die Selektion in horizontaler Richtung")

    LANG_C_H(SBMirrorV, EN, "", "Mirror vertical|Mirrors the selection in vertical direction")
    LANG_C_H(SBMirrorV, GE, "", "Spiegeln vertikal|Spiegelt die Selektion in vertikaler Richtung")

    LANG_C_H(SBRotate, EN, "", "Rotate|Rotates the square selection in clockwise direction")
    LANG_C_H(SBRotate, GE, "", "Rotieren|Rotiert die quadratische Selektion im Uhrzeigersinn")

    LANG_C_H(SBCentralsym, EN, "", "Central symmetric|Tries to make the selection central symmetric")
    LANG_C_H(SBCentralsym, GE, "", "Zentralsymmetrisch|Versucht die Selektion zentralsymmetrisch zu machen")

    LANG_C_H(SBHighlight, EN, "", "Highlight (F12)|Highlights the dependent parts")
    LANG_C_H(SBHighlight, GE, "", "Hervorheben (F12)|Hebt die abhängigen Teile hervor")

    Invalidate();
}
/*-----------------------------------------------------------------*/

 